"""remove column descrition from Item

Revision ID: 3ddcf4190b1a
Revises: 5e6917507781
Create Date: 2022-07-04 12:55:59.667923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddcf4190b1a'
down_revision = '5e6917507781'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_description', table_name='items')
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    # ### end Alembic commands ###
